# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for example
  pod 'Google-Mobile-Ads-SDK'
end
